[package]
name = "yeast"
version = "0.1.0"
authors = ["Olivier de Schaetzen <olivier4@telenet.be>"]
build = "build.rs"

[dependencies]
glfw = "*"
time = "*"

[build-dependencies]
gl_generator = "0.5.0"
